# the type of dynamic content
type: "shotgun_step"

# the shotgun field to use for the folder name
name: "other_steps"

filters:
    - { "path": "short_name", "relation": "not_in", "values": [ "UID", "MDL", "UUW", "REF" ] }