# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines related to Asset based work.

################################################################################

includes:
- ./includes/frameworks.yml
- ./includes/settings/tk-desktop2.yml
- ./includes/settings/tk-3dsmaxplus.yml
- ./includes/settings/tk-3dsmax.yml
- ./includes/settings/tk-houdini.yml
- ./includes/settings/tk-mari.yml
- ./includes/settings/tk-maya.yml
- ./includes/settings/tk-motionbuilder.yml
- ./includes/settings/tk-nuke.yml
- ./includes/settings/tk-photoshopcc.yml
- ./includes/settings/tk-aftereffects.yml
- ./includes/settings/tk-alias.yml
- ./includes/settings/tk-vred.yml
- ./includes/settings/tk-shell.yml
- ./includes/settings/tk-shotgun.yml

################################################################################
# configuration for all engines to load in an asset step context

engines:
  tk-desktop2: "@settings.tk-desktop2.all"
  tk-3dsmaxplus: "@settings.tk-3dsmaxplus.customentity02_step"
  tk-3dsmax: "@settings.tk-3dsmax.customentity02_step"
  tk-houdini: "@settings.tk-houdini.customentity02_step"
  tk-mari: "@settings.tk-mari.customentity02_step"
  tk-maya: "@settings.tk-maya.customentity02_step"
  tk-motionbuilder: "@settings.tk-motionbuilder.customentity02_step"
  tk-nuke: "@settings.tk-nuke.customentity02_step"
  tk-nukestudio: "@settings.tk-nuke.nukestudio.customentity02_step"
  tk-photoshopcc: "@settings.tk-photoshopcc.customentity02_step"
  tk-aftereffects: "@settings.tk-aftereffects.customentity02_step"
  tk-alias: "@settings.tk-alias.customentity02_step"
  tk-vred: "@settings.tk-vred.customentity02_step"
  tk-shell: "@settings.tk-shell.customentity02_step"
  tk-shotgun: "@settings.tk-shotgun.customentity02_step"

################################################################################
# reference all of the common frameworks

frameworks: "@frameworks"
