#MaterialLibrary

# the type of dynamic content
type: "shotgun_list_field"

# the shotgun entity type to connect to
entity_type: "CustomEntity01"

# the shotgun field to use for the folder name
field_name: "sg_resolution"

filters:
    - { "path": "project", "relation": "is", "values": [ "$material_library" ] }
    - { "path": "sg_master_material.CustomEntity01.code", "relation": "is", "values": [ "$parent_asset" ] }
    - { "path": "code", "relation": "is", "values": [ "$material" ] }
