name: Update Studio Dev

on:
  push:
    branches:
      - main  # Triggers on a push to the 'main' branch

jobs:
  push-to-studio-dev:
    runs-on: ubuntu-latest  # Specifies the runner

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v2
      # Checks out your repository

    - name: Push updates to Studio Dev
      run: |
        # Configures Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Adds studio-dev as a remote repository
        git remote add studio-dev https://x-access-token:${{ secrets.GitHub_Actions_Token }}@github.com/inquestudios/studio_dev.git
        
        # Fetches and pushes the changes
        git fetch studio-dev
        git push studio-dev main
