name: Update Studio Dev

on:
  push:
    branches:
      - main  # This workflow triggers on a push to the 'main' branch

jobs:
  push-to-studio-dev:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v2
      # Checks out your repository under $GITHUB_WORKSPACE

    - name: Push updates to Studio Dev
      run: |
        # Configures Git with GitHub Actions identity
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Adds studio-dev as a remote repository using the PAT for authentication
        git remote add studio-dev https://x-access-token:${{ secrets.clone_key }}@github.com/inquestudios/studio_dev.git
        
        # Fetches the branches and commits from the remote repository
        git fetch studio-dev
        
        # Pushes changes from the main branch of your repository to the main branch of studio-dev
        git push studio-dev main
